### PR TITLE
deps.windows: Add Zstandard

### PR DESCRIPTION
**Pull request by derrod**
### Description

Add static build of zstd for https://github.com/obsproject/obs-studio/pull/8074

### Motivation and Context

Want to make the world better.

### How Has This Been Tested?

Built locally, built OBS PR with built zstd.

### Types of changes

- New feature (non-breaking change which adds functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Review by RytoEX — APPROVED** [review]
Builds locally. Seems fine at a glance. @PatTheMav ?

**Comment by PatTheMav** [comment]
Does it install proper CMake packages? In that case we'd want to retain them in the obs-deps package so obs-studio's CMake picks it up without workarounds.

**Comment by derrod** [comment]
> Does it install proper CMake packages? In that case we'd want to retain them in the obs-deps package so obs-studio's CMake picks it up without workarounds.

It does as far as I am aware. It outputs some files in the `lib/cmake/zstd` folder and all I ended up having to do on the obs side was to add `find_package(zstd)` in the updater's cmake file.

**Comment by PatTheMav** [comment]
> > Does it install proper CMake packages? In that case we'd want to retain them in the obs-deps package so obs-studio's CMake picks it up without workarounds.
> 
> It does as far as I am aware. It outputs some `.cmake` files in the `lib/cmake/zstd` folder and all I ended up having to do on the obs side was to add `find_package(zstd)` in the updater's cmake file.

Nice, looks good to me then.

**Pull request merged**
