### PR TITLE
macos-deps: Add patched swig binary with support for Py3 stable ABI

### PR DESCRIPTION
**Pull request by PatTheMav**
### Description
Adds swig to precompiled binaries for macOS with applied patch for Py3 stable ABI patch.

### Motivation and Context
Support for the Python 3 stable ABI allows Python scripting support in OBS to use a wider range of available Python 3 versions vs. being pinned to the version the scripting module is compiled with.

The patch represents an updated and unmerged PR (https://github.com/swig/swig/pull/2190) to add this support to swig.

**NOTE:** Swig compiled on UNIX systems hardcodes the swig library path from the host system. Building obs-scripting and its modules with this version requires additional changes to the obs-studio build scripts to override the `SWIG_LIB` path per make build configuration.

### How Has This Been Tested?
* Built locally
* Built OBS with precompiled swig binary

### Types of changes
- New feature (non-breaking change which adds functionality)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Review by RytoEX — APPROVED** [review]
Looks fine to me at a glance.

**Comment by PatTheMav** [comment]
https://github.com/obsproject/obs-studio/pull/6682 adds the necessary "fix" to the main repo to support obs-deps with this added.

**Comment by emaste** [comment]
Is this handled for Linux somehow as well, or is it currently possible to build on macOS/Windows only at the moment?
(On FreeBSD I get `swig error : Unrecognized option -py3-stable-abi`)

**Comment by WizardCM** [comment]
OBS should still build, SWIG should just ignore the flag afaik.

**Comment by emaste** [comment]
swig 4.0.2 on FreeBSD fails due to the unrecognized option anyway

**Pull request merged**
