### PR TITLE
Update all deps

### PR DESCRIPTION
**Pull request by RytoEX**
### Description

Update as many of our dependencies as possible to either the latest stable or latest git commit.

* utils.pwsh: Add support for 7z to extract exe files
* deps.ffmpeg: Update zlib to 1.2.12
* deps.ffmpeg: Update opus to ab04fbb1b7
* deps.ffmpeg: Update libogg to 1.3.5 on Windows
* deps.ffmpeg: Update libvorbis to 84c023699c on Windows
* deps.ffmpeg: Update libvpx to 1.12.0
* deps.ffmpeg: Update SVT-AV1 to 1.1.0
* deps.ffmpeg: Update aom to 3.4.0
* deps.ffmpeg: Update x264 to r3095
* deps.ffmpeg: Update mbedTLS to 2.28.1
* deps.ffmpeg: Update mbedTLS to 3.1.0
* deps.ffmpeg: Update mbedTLS to 3.2.1
* deps.ffmpeg: Update libsrt to 1.5.0
* deps.ffmpeg: Update librist to 809390b3b7
* deps.ffmpeg: Update AMF to 1.4.24
* deps.ffmpeg: Update FFmpeg to 5.0.1
* deps.ffmpeg: Remove unused Vulkan checksum file
* deps.macos: Update SpeexDSP to 1.2.1
* deps.macos: Update Jansson to 2.14
* deps.macos: Update LuaJIT to 2.1 3065c910ad
* deps.macos: Update FreeType to 2.12.1
* deps.macos: Remove unused Qt checksum files
* deps.windows: Update mbedTLS to 3.2.1
* deps.windows: Update FreeType to 2.12.1
* deps.windows: Update cmocka to bbf5ff7dd5
* deps.windows: Update curl to 7.84.0
* deps.windows: Update SpeexDSP to 1.2.1
* deps.windows: Update Detours to 24357c6a5a
* deps.windows: Update LuaJIT to 2.1 3065c910ad
* deps.windows: Update VulkanSDK to 1.3.216.0
* deps.windows: Update nasm to 2.15.05
* deps.windows: Update Python to 3.8.10
* deps.windows: Remove unused SWIG checksum file
* deps.qt: Update Qt5 to Qt 5.15.5 for Windows
* deps.qt: Update Qt6 to Qt 6.3.1 for Windows
* deps.qt: Update Qt5 to Qt 5.15.5 for macOS
* deps.qt: Update Qt6 to Qt 6.3.1 on macOS

### Motivation and Context

Want to keep our deps up to date. Up to date deps come with bug fixes, new features, and allow us to maintain less patches and backport less commits/patches.

### How Has This Been Tested?

I have tested this locally on Windows 11 against recent commits of OBS Studio.

#### Good news

OBS builds.

These worked:
* Encoders
  * AOM
  * SVT-AV1
  * AMF
  * NVENC
  * x264
* Recording
  * Standard
  * Custom FFmpeg Output
* Streaming
  * RTMPS (works with mbedTLS 2.28.1, but not 3.2.1) [1]
  * HLS
  * SRT (local network)
* Sources
  * Browser
    * Default
    * FishGL/Aquarium
  * Color
  * Display Capture
    * WGC
  * Game Capture
  * Image
    * Animated GIF
    * JPG
    * PNG
  * Image Slide Show
  * Media
    * FLV
    * MP4
    * SRT ingest on local network (Larix Broadcaster/Screencaster)
    * RIST ingest on local network (OBS to OBS)
    * webm with transparency
  * Text (FreeType 2)
  * Text (GDI+)
  * Video Capture Device
  * VLC
    * playlist of files
  * Window Capture
    * BitBlt
    * WGC
 * Filters
   * Chroma Key
   * Color Correction
 * webm stingers

#### Bad news

These did not work:
* ~~Streaming~~
  * ~~RTMPS (works with mbedTLS 2.28.1, but not 3.2.1) [1]~~

For this reason, I've split the mbedTLS updates into multiple commits so that we can easily drop them or stash them for later.
* https://github.com/obsproject/obs-studio/pull/6785
* The mbedTLS fix PR was merged, so RTMPS works fine now with mbedTLS 2.28.1 and 3.1.0+.

#### Not yet tested

* Virtual Camera

[1]: I've opened a PR on obs-studio to fix the issue with mbedTLS 3.2.1:
* https://github.com/obsproject/obs-studio/pull/6785

### Types of changes

- New feature (non-breaking change which adds functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by RytoEX** [comment]
I've opened a PR on obs-studio to fix the issue with mbedTLS 3.2.1:
* https://github.com/obsproject/obs-studio/pull/6785

**Comment by RytoEX** [comment]
FFmpeg n5.1 was recently released, so I have updated this PR accordingly. This allows us to drop yet another patch and leaves us only with two trivial FFmpeg patches.

**Comment by tytan652** [comment]
0001-FFmpeg-9010.patch can be removed too, it is in 5.1.

https://github.com/FFmpeg/FFmpeg/commit/f1c19867d72a14699277175101b2bcf1e333af88

**Comment by RytoEX** [comment]
> 0001-FFmpeg-9010.patch can be removed too, it is in 5.1.
> 
> [FFmpeg/FFmpeg@f1c1986](https://github.com/FFmpeg/FFmpeg/commit/f1c19867d72a14699277175101b2bcf1e333af88)

Have fixed locally and will re-push once CI finishes its current run.

**Comment by RytoEX** [comment]
Upon retesting FFmpeg 5.1, it seems that deprecations in swresample will need changes in obs-studio before we can use it. If we cannot resolve that easily/quickly, I am prepared to use FFmpeg 5.0.1 instead for now, which is still a nice upgrade and still lets us drop the majority of our patches.

**Pull request merged**
