### PR TITLE
Update macOS minimum targets from 10.11 to 10.13

### PR DESCRIPTION
**Pull request by RytoEX**
### Description

Update the minimum macOS build targets from 10.11 to 10.13.

### Motivation and Context

OBS officially only supports 10.13+ because Qt 5.14.x only supports 10.13+.  Let's just make sure everything is targeting that minimum so that we (hopefully) get the benefits of targeting a newer minimum.

### How Has This Been Tested?

I haven't tested this because I don't have access to a Mac.  We should test against deps built this way, but this shouldn't really change anything.

### Types of changes

- Performance enhancement (non-breaking change which improves efficiency)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [ ] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by RytoEX** [comment]
The CI may fail due to git.xiph.org outages.

A thought:  could we not reuse `MACOSX_DEPLOYMENT_TARGET` in all the other places in the script?

Also, I think the main OBS repo CI similarly targets older macOS/OSX versions, and those should probably also be updated.

**Comment by PatTheMav** [comment]
Good idea - had it integrated in my PR and also applied the idea to reuse it were appropriate.

**Comment by RytoEX** [comment]
I still need to go make the complementary PRs for obs-studio and obs-browser so that everything is using the same minimum, and then ideally all of them should be merged around the same time.

**Comment by RytoEX** [comment]
Since this is changing an obsolete file, is this even worth keeping open or merging?  Should we just remove obsolete files instead?

**Comment by PatTheMav** [comment]
Yeah go ahead and do the deprecation. I actually prefer you doing that as I might be "institutionally blind" in this regard already.

**Comment by RytoEX** [comment]
> Since this is changing an obsolete file, is this even worth keeping open or merging? Should we just remove obsolete files instead?

> Yeah go ahead and do the deprecation. I actually prefer you doing that as I might be "institutionally blind" in this regard already.

Submitted this removal as #52.

**Pull request closed without merging**
