### PR TITLE
Revert Qt 6.7 update

### PR DESCRIPTION
**Pull request by RytoEX**
### Description

Revert the Qt 6.7 update which updated from Qt 6.6.3 to 6.7.2.

### Motivation and Context

Due to issues on Windows 11, revert this update for now. See:
* https://bugreports.qt.io/browse/QTBUG-128517
* https://bugreports.qt.io/browse/QTBUG-128518

### How Has This Been Tested?

Qt 6.6.3 has been used in previous OBS Studio releases.

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by sudopluto** [comment]
QTBUG-128517: fixed in qt6.8.1:
https://bugreports.qt.io/browse/QTBUG-128517

QTBUG-128518: open pull requests, not yet merged
https://bugreports.qt.io/browse/QTBUG-128518

will start testing flatpak with qt 6.8.X since that looks like when it will be fixed

**Comment by sudopluto** [comment]
both bug fixes have been merged into future qt 6.8.1 release

**Comment by RytoEX** [comment]
I am subscribed to those QTBUGs and track their progress regularly and get notifications for them. I appreciate the effort, but I do not require additional notifications for them.

As for updating to Qt 6.8.x, 6.8.1 is not due for release until November 21, 2024. As such, that is the earliest point at which we would attempt to update Qt for all three platforms. Thank you for your understanding.

**Comment by sudopluto** [comment]
@RytoEX 

the release was pushed earlier this month, please let me know if you would like a tester for both windows & linux

https://www.qt.io/blog/qt-6.8.1-released

**Pull request merged**
