### PR TITLE
windows-deps: Add patched swig binary with support for Py3 stable ABI

### PR DESCRIPTION
**Pull request by PatTheMav**
### Description
Adds swig to precompiled binaries for Windows with applied patch for Py3 stable ABI patch.

### Motivation and Context
Support for the Python 3 stable ABI allows Python scripting support in OBS to use a wider range of available Python 3 versions vs. being pinned to the version the scripting module is compiled with.

### How Has This Been Tested?
* Built and packaged Swig locally
* Compiled obspython with Swig compiled with these changes

### Types of changes
- New feature (non-breaking change which adds functionality)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by jp9000** [comment]
Big hype. Can't wait until this is merged.

**Comment by RytoEX** [comment]
Is this until SWIG merges the needed stable ABI PR, or does this also require an additional patch that it yet to be upstreamed (PR'd/merged)?

**Comment by PatTheMav** [comment]
> Is this until SWIG merges the needed stable ABI PR, or does this also require an additional patch that it yet to be upstreamed (PR'd/merged)?

This just contains the PR re-based on master. It was easier to apply it as a single patch on master vs checking out the PR, then patching it further.

The patch is identical to the one on macOS apart from Windows line endings.

**Comment by RytoEX** [comment]
There are two patches here though. Is the second one part of the aforementioned SWIG PR, or is it something completely separate that we have to maintain?

**Comment by PatTheMav** [comment]
> There are two patches here though. Is the second one part of the aforementioned SWIG PR, or is it something completely separate that we have to maintain?

The second patch mainly fixes their CMakeLists script to work with the PCRE2 library as produced by PCRE itself. This is mainly due to Swig not maintaining a build script that works with the Windows libraries produced by PCRE out of the box.

Their docs otherwise require to pass the necessary variables manually (i.e. `-DCMAKE_C_FLAGS="/DPCRE2_STATIC" ^
-DCMAKE_CXX_FLAGS="/DPCRE2_STATIC" -DPCRE2_INCLUDE_DIR=%PCRE_ROOT%/include -DPCRE2_LIBRARY=%PCRE_ROOT%/lib/pcre2-8-static.lib`) which I found too brittle.

A fix would be to update Swig's CMakeLists file upstream to work with PCRE as produced by their build system out of the box on Windows.

**Review by RytoEX — APPROVED** [review]
PR looks fine to me. My one ask would be to upstream the additional patch to SWIG and hope that they merge it in the future.

**Comment by RytoEX** [comment]
Per off-thread conversation with @PatTheMav , he will clean up and upstream the CMake patch at a later date. Merging.

**Pull request merged**
