### PR TITLE
deps.ffmpeg: Add libdatachannel licenses

### PR DESCRIPTION
**Pull request by RytoEX**
### Description

Correct an oversight from the PR that added libdatachannel (#170). The license file was not added then, so let's add it now.

### Motivation and Context

Want component licenses properly documented.

### How Has This Been Tested?

n/a

### Types of changes

- Documentation (a change to documentation pages)

### Checklist:

- [ ] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by RytoEX** [comment]
I have no idea the state of the deps of libdatachannel. @DDRBoxman @pkviet ?

**Comment by pkviet** [comment]
@RytoEX 
usrsctp: <https://github.com/sctplab/usrsctp/blob/master/LICENSE.md>
Plog : mit
Libjuice: mpl 2.0
Libsrtp : <https://github.com/cisco/libsrtp/blob/main/LICENSE>
Nlohman json: MIT

No idea whether usrsctp and libsrtp are gpl compatible...
Maybe Sean will be able to tell.

**Comment by Sean-Der** [comment]
@RytoEX they are all GPL compatible!

usrsctp and libsrtp are both 3 clause BSD.

**Comment by RytoEX** [comment]
I've now added all license files for libdatachannel and its deps from the pinned commit that we currently use.

**Review by PatTheMav — APPROVED** [review]

**Pull request merged**
