### PR TITLE
Update Swig to 4.1.1 on Windows and macOS

### PR DESCRIPTION
**Pull request by PatTheMav**
### Description
Updates Swig to 4.1.1 on Windows and macOS including an updated stable ABI patch.

### Motivation and Context
Stay up-to-date with upstream project.

### How Has This Been Tested?
Built and tested scripting with updated swig runtime on macOS and Windows.

### Types of changes
- Tweak (non-breaking change to improve existing functionality)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by PatTheMav** [comment]
@RytoEX I'd guess we look into merging this post v29 as well?

**Comment by RytoEX** [comment]
Once I've had a chance to test it, yeah.

**Comment by PatTheMav** [comment]
Depends on https://github.com/obsproject/obs-studio/pull/8184

**Comment by RytoEX** [comment]
> Depends on [obsproject/obs-studio#8184](https://github.com/obsproject/obs-studio/pull/8184)

Even with that PR now merged, I still get build errors on Windows 11.
```
  Swig compile obspython.i for python
  Building Custom Rule C:/Users/rytoex/Documents/code/obsproject/obs-studio/deps/obs-scripting/obspython/CMakeLists.txt
  cstrcache.cpp
  obspythonPYTHON_wrap.c
C:\dev\obsproject\obs-studio\build64\deps\obs-scripting\obspython\CMakeFiles\obspython.dir\obsp
ythonPYTHON_wrap.c(1495,23): error C2059: syntax error: '}' [C:\dev\obsproject\obs-studio\build
64\deps\obs-scripting\obspython\obspython.vcxproj]
C:\dev\obsproject\obs-studio\build64\deps\obs-scripting\obspython\CMakeFiles\obspython.dir\obsp
ythonPYTHON_wrap.c(2114,23): error C2059: syntax error: '}' [C:\dev\obsproject\obs-studio\build
64\deps\obs-scripting\obspython\obspython.vcxproj]
C:\dev\obsproject\obs-studio\build64\deps\obs-scripting\obspython\CMakeFiles\obspython.dir\obsp
ythonPYTHON_wrap.c(2321,23): error C2059: syntax error: '}' [C:\dev\obsproject\obs-studio\build
64\deps\obs-scripting\obspython\obspython.vcxproj]
C:\dev\obsproject\obs-studio\build64\deps\obs-scripting\obspython\CMakeFiles\obspython.dir\obsp
ythonPYTHON_wrap.c(2672,37): error C2037: left of 'tp_new' specifies undefined struct/union '_typeobject' [C:\Users\ryt
oex\Documents\code\obsproject\obs-studio\build64\deps\obs-scripting\obspython\obspython.vcxproj]
C:\dev\obsproject\obs-studio\build64\deps\obs-scripting\obspython\CMakeFiles\obspython.dir\obsp
ythonPYTHON_wrap.c(2754,41): error C2037: left of 'tp_alloc' specifies undefined struct/union '_typeobject' [C:\Users\r
ytoex\Documents\code\obsproject\obs-studio\build64\deps\obs-scripting\obspython\obspython.vcxproj]
```

**Pull request closed without merging**
