### PR TITLE
Build Script for Windows OBS Dependencies

### PR DESCRIPTION
**Pull request by Xaymar**
### Description
This is a simple build script to generate all necessary dependencies for OBS Studio on windows, using mingw64 on Ubuntu. I've chosen to use submodules here so that individual version updates for dependencies don't require a massive commit, bloating the main obs-deps repository.

With this script (and the use of Github Releases), OBS could finally move away from the dependencies.zip file that randomly changes with no warning ahead of time. Or any way to get an older version of it.

### Motivation and Context
During the beta development of OBS Studio 24.0.0, someone uploaded a new dependencies.zip, which meant that my CI (AppVeyor, Github Actions) was now using dependencies from 24.0.0, but was trying to build compatible binaries for 23.0.0. This was really annoying, and completely unexpected, especially since you would normally expect to get the dependencies.zip for the currently released version, instead of a future release version.

### How Has This Been Tested?
Still heavy work in progress.

### Types of changes
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Performance enhancement (non-breaking change which improves efficiency)
- Code cleanup (non-breaking change which makes code smaller or more readable)
- Breaking change (fix or feature that would cause existing functionality to change)
- Documentation (a change to documentation pages)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.

### Dependencies Built:
- [x] curl
  - [x] with mbedtls
  - [x] with zlib
- [x] ffmpeg
  - [x] nvenc
  - [ ] amf
  - [x] libx264
  - [x] libvpx
  - [x] libopus
  - [x] libvorbis
  - [x] srt
  - [x] zlib for png
- [x] freetype
- [x] libpng
  - [ ] apng support
- [x] luajit
- [x] mbedtls
  - [x] with zlib
- [x] ogg
- [x] opus
- [x] python3
- [x] srt
- [x] vorbis
- [x] vpx
- [ ] websockets
- [x] zlib
- [x] swig
  - [x] python
  - [x] luajit

### CODE REVIEW

**Comment by Xaymar** [comment]
Note, this is a _heavy work in progress_. So far it only builds the absolute minimum required to get things to work, there is a lot of work left (including squashing commits).

**Comment by Xaymar** [comment]
Current Problems:

- zlib thinks we are on unix, despite a cross-compiler toolchain being present.
- mbedTLS has no key exchanges or anything enabled.

**Comment by Xaymar** [comment]
The `srt` library is currently causing ffmpeg to link against libstdc++ libgcc_s_seh and various other libraries that are unwanted for no real reason. It should not need any of those, especially not libgcc_s_seh

**Comment by Xaymar** [comment]
For interested people, this is the current state (win64): 
[obs.zip](https://github.com/obsproject/obs-deps/files/3775031/obs.zip)

Contains ffmpeg (with srt, nvenc, x264, vp8, vp9, vorbis, ogg, opus, png, apng), srt, vp8, vp9, x264, vorbis, ogg, opus, libpng, zlib, mbedtls, mbedx509 and mbedcrypto. Most things have a static and dynamic version, though ffmpeg is linked dynamically for the sake of size and compatibility.

A patch for obs-studio is also required due to the new dll names: 
[0001-update-deps.zip](https://github.com/obsproject/obs-deps/files/3775036/0001-update-deps.zip)

**Comment by Xaymar** [comment]
The `win-cross-compile.sh` script now has various arguments in order to support multiple architectures, quiet and verbose builds and various other things. It is also now possible to specify the intermediate build and final output directories, which should help with packaging in CI and other places.

**Comment by Xaymar** [comment]
The `win32` generated dependencies currently link against libgcc_s_sjlj.dll, but they should be statically linking to it instead. Not sure how to fix that.

**Comment by Xaymar** [comment]
I've added Github Actions support with automatic packaging for a win-deps.7z file, for use in obs-studio. Building takes around 20 minutes on Github Actions, and times out on AppVeyor like expected.

**Comment by Xaymar** [comment]
Unfortunately cross-compiling Python seems to be unsupported, even the fan-made cmake build system for python does not work and assumes that it runs on windows, even though it's actually in a cross-compiling environment. I will exclude Python for that reason for now.

**Comment by Xaymar** [comment]
Nevermind, just took the python3.lib and python36.lib from the 3.6.7 release exe and uploaded them somewhere.

**Comment by Xaymar** [comment]
Marking this as ready for review, even though not everything is in yet. LuaJIT requires to be compiled on Windows, so I have to work on splitting off the windows-exclusive builds to a 2nd script.

**Comment by Xaymar** [comment]
Aditionally I have no idea how to build libcurl and libmbedtls with support for the Windows CA cert store. It wants a ca-cert-bundle.crt, but obs-studio doesn't ship with one IIRC.

**Comment by Xaymar** [comment]
@DDRBoxman Do you happen to have a way to compile websockets or know someone that actually managed to do so? It seems to be failing with a nonsense linker error that I haven't seen before, and doesn't happen in anything else that links to libmbedx509

**Comment by SCG82** [comment]
Can swig (https://github.com/swig/swig) be used as a submodule?

**Comment by Xaymar** [comment]
From the problems I encountered with it, no.

**Comment by Xaymar** [comment]
Closing as I have no further interest in this matter.

**Pull request closed without merging**
