### PR TITLE
CI: Update to Qt 5.15.2 for macOS

### PR DESCRIPTION
**Pull request by PatTheMav**
### Description
Updates Qt to 5.15.2 as part of prebuilt dependencies.

### Motivation and Context
Prepares for milestone 26.1 as discussed in https://github.com/obsproject/obs-studio/issues/3752.

### How Has This Been Tested?
* Qt built locally
* OBS built with most recent deps and Qt
* OBS launched
* Checked VirtualCamera
* Checked Recording
* Checked Streaming (local SRT server)

### Types of changes
- New feature (non-breaking change which adds functionality)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by DDRBoxman** [comment]
Leaving a note here that we need 5.15 for Apple silicon fixes 😎

**Comment by RytoEX** [comment]
A bit late to be asking, I suppose, but is there a reason we load the Qt patch from a gist instead of including it in the repo?

**Comment by PatTheMav** [comment]
Mainly because I wanted to use the `apply_patch` thing that expects a GitHub diff. As there was no straight diff available, this was the next simpler thing.

**Comment by RytoEX** [comment]
I'm not sure I follow.  The `apply_path` utility takes a URL and a hash.  Could we not do this?

```
${{ github.workspace }}/utils/apply_patch "https://raw.githubusercontent.com/obsproject/obs-deps/master/patch/obs-issue-3799-qt.patch" "234ee6b21a008a233382c872ac097707ce83e401d3bcd5f1b244c09c0817f3aa"
```

Or we could commit the patch as its own commit and use GitHub's .patch URL?

I'm just not fond of patches living outside the repo if we can help it.  Also, not that we're building on 5.14.1 anymore, but the issue that the patch fixes affected 5.14.1 as well, but the patch is only applied to Qt versions other than 5.14.1.  We'd need a different patch to apply to 5.14.1 if we were still supporting it, but we could just rip out the 5.14.1 sections as well.

**Comment by PatTheMav** [comment]
> I'm not sure I follow. The `apply_path` utility takes a URL and a hash. Could we not do this?
> 
> ```
> ${{ github.workspace }}/utils/apply_patch "https://raw.githubusercontent.com/obsproject/obs-deps/master/patch/obs-issue-3799-qt.patch" "234ee6b21a008a233382c872ac097707ce83e401d3bcd5f1b244c09c0817f3aa"
> ```
> 
> Or we could commit the patch as its own commit and use GitHub's .patch URL?
> 
> I'm just not fond of patches living outside the repo if we can help it. Also, not that we're building on 5.14.1 anymore, but the issue that the patch fixes affected 5.14.1 as well, but the patch is only applied to Qt versions other than 5.14.1. We'd need a different patch to apply to 5.14.1 if we were still supporting it, but we could just rip out the 5.14.1 sections as well.

We could and I wasn't just as smart as you just where with this idea. Love it.. :D

**Comment by RytoEX** [comment]
> We could and I just wasn't as smart as you just where with this idea. Love it.. :D
> 
> We just would've needed to commit the file before committing the PR.

No worries.  We can move to that later then.  I'd much prefer keeping as much of the obs-deps data together as possible.

**Pull request merged**
