### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by RytoEX**
### Description

Update as many dependencies as we are able to update. Some commits taken from @PatTheMav 's fork at his suggestion.
* deps.ffmpeg: Update zlib to 1.2.13
* deps.ffmpeg: Update libpng to 1.6.38
* deps.ffmpeg: Update opus to bce1f39235
* deps.ffmpeg: Update SVT-AV1 to 1.3.0
* deps.ffmpeg: Update aom to 3.5.0
* deps.ffmpeg: Update x264 to r3101
* deps.ffmpeg: Add virtual x264 package to create Windows DLL
* deps.ffmpeg: Update libsrt to 1.5.1
* deps.ffmpeg: Update AMF to 1.4.26
* deps.ffmpeg: Update FFmpeg to 5.1.2
* deps.macos: Update LuaJIT to 2.1 6c4826f12c
* deps.macos: Update libpng to 1.6.38
* deps.windows: Update cmocka to cd95ee9f77
* deps.windows: Update curl to 7.86.0
* deps.windows: Update LuaJIT to 2.1 6c4826f12c
* deps.windows: Update pyenv-win to 3.1.1
* deps.qt: Update Qt5 to Qt 5.15.7 for Windows
* deps.qt: Update Qt6 to Qt 6.4.1 for Windows
* deps.qt: Update Qt5 to Qt 5.15.7 for macOS
* deps.qt: Update Qt6 to Qt 6.4.1 for macOS 

### Motivation and Context

Want to stay up to date. We're pretty sure that there are at least a few issues will be resolved by updating FFmpeg, for example:
* obsproject/obs-studio#6974
* obsproject/obs-studio#7449

The more we stay up to date, the less difficult it is to update. Staying up to date means maintaining less patches. This set of updates lets us drop seven patches, though admittedly four of those are for Qt5 (which we no longer use on either Windows or macOS).

This will likely be expedited so we can iterate on these updates and find out what works and doesn't. If we have to rollback or adjust any deps, I think it's better to get the updated deps into obs-studio CI builds to widen the testing pool sooner rather than later.

### How Has This Been Tested?

Have built the Windows deps locally (both the native-built deps and the FFmpeg cross-compiled chain of deps), and have also successfully built these deps on my fork's CI. Have not yet tested them against OBS. I wanted to get the PR in front of others first to give others a chance to test if they have time.

### Checklist:

- [ ] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by tommyvct** [comment]
Should my Windows ARM64 PR be merged before this, or after?

**Comment by RytoEX** [comment]
> Should my Windows ARM64 PR be merged before this, or after?

After. We're targeting deps updates for OBS 29. I don't think we'll have time to review WoA stuff before the feature freeze.

**Comment by RytoEX** [comment]
I've dropped the SWIG updates since they were causing build problems with OBS. We can revisit this later.

I've bumped the following:
* LuaJIT to 7a0cf5fd4c
* Qt6 to 6.4.1

I have been running into an assert when building OBS in Debug configuration against Qt 6.4.0. Hopefully this is resolved in Qt 6.4.1, or else I may have to consider pushing a Qt update to a later release.

**Comment by RytoEX** [comment]
While I have been testing these against OBS Studio, I apparently never posted a list of my test results. From my recollection, the only things that did not work in my tests were scripting stuff and SVT-AV1. I've since dropped the SWIG update to avoid the former, and I've since fixed the latter in a PR to OBS Studio.

#### Good news

OBS builds.

These worked:
* Encoders
  * AOM
  * SVT-AV1 (except CBR) [1]
  * AMF
  * NVENC
  * x264
* Recording
  * Standard
  * Custom FFmpeg Output
* Streaming
  * RTMP
  * RTMPS
  * HLS
  * SRT (local network)
  * RIST (local network)
* Sources
  * Browser
    * Default
    * FishGL/Aquarium
  * Color
  * Display Capture
    * WGC
  * Game Capture
  * Image
    * Animated GIF
    * JPG
    * PNG
  * Image Slide Show
  * Media
    * FLV
    * MP4
    * SRT ingest on local network (OBS to OBS)
    * RIST ingest on local network (OBS to OBS)
    * webm with transparency
  * Text (FreeType 2)
  * Text (GDI+)
  * Video Capture Device
  * VLC
    * playlist of files
  * Window Capture
    * BitBlt
    * WGC
 * Filters
   * Chroma Key
   * Color Correction
 * webm stingers
 * Scripting
   * Python
   * Lua


#### Bad news

These did not work:
* Encoders
  * SVT-AV1 (CBR) [1]

[1]: I've opened a PR on obs-studio to fix the issue with SVT-AV1 CBR:
* https://github.com/obsproject/obs-studio/pull/7799

**Pull request merged**
