### PR TITLE
deps.ffmpeg: Update AMF to 1.4.29

### PR DESCRIPTION
**Pull request by tytan652**
### Description

Update AMF to version 1.4.29 to make https://github.com/obsproject/obs-studio/pull/6927 works.

Difference between upstream and "external" from OBS Studio repo:
- "external" have outdated code compared to 1.4.28 from upstream
- This [enum value](https://github.com/obsproject/obs-studio/blob/48b5fd5a3ba115b4bf9dc84c17d28d8febfd9e99/plugins/obs-ffmpeg/external/AMF/include/components/HQScaler.h#L48) that is not present upstream and is unused in OBS Studio whole repo (the header itself is not used), so it's removal is seamless.

How ?:
I pasted 1.4.28 over our "external" version and each diff (except the enum value) happen to be new code because if I blame upstream code and check the prior code, the prior code match "external".

And `AMF_HQ_SCALER_ALGORITHM_FSR1_1` looks completely unused when I search in OBS Studio repo locally.

### Motivation and Context

Make https://github.com/obsproject/obs-studio/pull/6927 works.

### How Has This Been Tested?

Custom release on my fork and https://github.com/obsproject/obs-studio/pull/6927.
Binaries on linked PR may need testing.

### Types of changes

- Tweak (non-breaking change to improve existing functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by PatTheMav** [comment]
Change itself looks fine to me - would updating obs-deps with this break anything with obs-studio as is (wasn't entirely clear to me from the OP).

**Comment by tytan652** [comment]
No breakage, OBS Studio still use the integrated AMF and it is planned to be also updated to the real 1.4.29.

**Review by PatTheMav — APPROVED** [review]
Looks fine to me - @RytoEX any objections?

**Comment by RytoEX** [comment]
No objections. I just keep having other things come up. Will get to this today.

**Review by RytoEX — APPROVED** [review]

**Pull request merged**
